#!/bin/bash
#
# Provides short mappings for common Git commands
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
# #

__git-short_docomplete ()
{
  complete -o bashdefault -o default -o nospace -F $2 $1 2>/dev/null \
    || complete -o default -o nospace -F $2 $1
}

__git-short_shortmap ()
{
  # only perform completion when within a git dir
  __gitdir >/dev/null || return $?

  # execute the associated completion function (column two of the shortmaps
  # file)
  $( awk "/^$1 / { print \$2 }" <<< "$__git_short_maps" )
}

# load shortmaps from cwd (or provided path) and home dir (if available)
__git_short_maps=$( cat ${1:-.}/shortmaps ~/.git-shortmaps 2>/dev/null )


# register each shortmap
IFS=$'\n'
for line in $__git_short_maps; do
  IFS=$' '
  set -- $line
  short=$1

  __git-short_docomplete "$1" __git-short_shortmap

  shift 2
  alias $short="$( sed 's/^:/git /' <<< "$@" )"
done

